[package]
name = "bite"
version = "0.3.0"
authors = ["Andrés Villalobos <andresalvivar@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polling = "2.5.2"
serde_json = "1.0.93"
crossbeam-channel = "0.5.6"
bincode = "1.3.3"
