[package]
name = "bite"
version = "0.1.0"
authors = ["Andrés Villalobos <andresalvivar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.64"
crossbeam-channel = "0.5.1"
tungstenite = "0.13.0"
url = "2.1.0"
log = "0.4.14"
env_logger = "0.8.3"

[workspace]
members = ["server", "client", "wsserver", "wsclient"]

[[bin]]
name = "server"
path = "server/src/main.rs"

[[bin]]
name = "client"
path = "client/src/main.rs"

[[bin]]
name = "wsserver"
path = "wsserver/src/main.rs"

[[bin]]
name = "wsclient"
path = "wsclient/src/main.rs"
