[package]
name = "bite"
version = "0.1.0"
authors = ["Andrés Villalobos <andresalvivar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio = { version = "0.7.11", features = ["net", "os-poll"] }
crossbeam-channel = "0.5.1"
serde_json = "1.0.64"
env_logger = "0.8.4"

[workspace]
members = ["server", "client"]

[[bin]]
name = "server"
path = "server/src/main.rs"

[[bin]]
name = "client"
path = "client/src/main.rs"
