version: '3.3'
services:
  bite:
    container_name: bt
    build: ./server/
    ports:
      - '1984:1984'
    volumes:
      - ./data:/data
    restart: on-failure
  bite_jsyc:
    container_name: bj
    build: ./server/
    ports:
      - '1985:1984'
    volumes:
      - ./data_jsyc:/data
    restart: on-failure
