version: '3.8'
services:
    bite:
        container_name: bite
        build: https://github.com/alvivar/bite.git
        ports:
            - '1984:1984'
        volumes:
            - ./data:/data
        environment:
            - SERVER=0.0.0.0:1984
            - RUST_LOG=info
        restart: unless-stopped
