version: '3.8'
services:
    bite:
        container_name: bite
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - '1984:1984'
        volumes:
            - type: bind
              source: ./data
              target: /data
        environment:
            - RUST_LOG=info
            - SERVER=0.0.0.0:1984
        restart: unless-stopped
